"""Initial migration.

Revision ID: e4eb6fc09c9f
Revises: 
Create Date: 2025-01-31 19:38:29.192431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eb6fc09c9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photoOfTheRecipe', sa.String(length=200), nullable=True),
    sa.Column('nameOfTheRecipe', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('teacher', sa.String(length=10), nullable=True),
    sa.Column('ingredient', sa.String(length=200), nullable=True),
    sa.Column('steps', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
